### ISSUE TITLE
eucast_rules() throws an error

### ISSUE THREAD

**Issue by nrkoehler** [msberends/AMR#16]
The following code throws an error message:
library(AMR)
library(tidyverse)
oops <- data.frame(mo = c("Klebsiella", 
                          "Escherichia"), ampicillin = "S")
oops

eucast_rules(oops, info = FALSE)

The message (in german) is: 

Fehler in value[[3L]](cond) : 
  ungültiger regulärer Ausdruck '^(abbotic|abboticin|abdizide|abelcet|abelecet|abomacetin|acetohmt|acetylspiramycin|acideclavulanique|acidefusidique|acidoclavulanico|acidofusidico|acidomandelico|acidumclavulanicum|acidumfusidicum|acillin|acneryne|acnesol|acromona|acronize|actilin|actiline|actimoxi|aczone|adesulfonesodium|adobacillin|advocin|aeroquin|aethambutolum|aethionamidum|aetina|aetiva|aizumycin|aknecordeslosung|aknedermerygel|aknemycin|alcephin|alcobon|alconcilox|aldapsone|aldesulfonasodica|aldesulfone|aldesulfonesodique|aldesulfonesodium|alenfral|alexin|alfacet|alficetyn|alflucoz|alfumet|aliporina|almitil|almondacid|alsporin|altacef|ambisome|amblosin|ambofen|ambrocef|ambylan|amcill|amdinocillin|amfipen|amfipenv|amfotericinab|amicacin|amidazin|amidazine|amikacillin|amikacin|amikacinbase|amikacindihydrate|amikacinsulfate|amikacina|amikacine|amikacinum|amikavet|amikin|amiklin|amikozit|aminodeoxykanamycin|aminoform|aminoformaldehyde|aminopar|aminosalicylic|aminosalicylicaci

It seems to be an unvalid regular expression.

Is this error reproducible?

**Comment by msberends** [comment]
Thanks for using the package! I think this was fixed in our previous version, v1.3.0.

Could you try again by running install.packages("AMR"), restart R and try again?

**Comment by msberends** [comment]
### 📋 Please take part in our survey!
Now you're at it, please fill in [our short questionnaire](https://msberends.github.io/AMR/survey.html)! You can fill it in completely anonymously. If you know others using this `AMR` package, please ask them to fill it in too. 

Your valuable input will help to improve the package and its functionalities 🙂

**Comment by msberends** [comment]
This cannot be reproduced with AMR 1.40, that was released on CRAN today.

**Comment by msberends** [comment]
### Fix released to official R repository
Just a small notice: we released a new software version, containing the fix to this issue. Please update your version using either the user interface of your software, or by running:
```r
install.packages("AMR")
```

**Comment by nrkoehler** [comment]
I'm still getting the same error message when using AMR version 1.3

```
  a <- data.frame(mo = c("Staphylococcus aureus",
                         "Enterococcus faecalis",
                         "Escherichia coli",
                         "Klebsiella pneumoniae",
                         "Pseudomonas aeruginosa"),
                  VAN = "-",       # Vancomycin
                  AMX = "-",       # Amoxicillin
                  COL = "-",       # Colistin
                  CAZ = "-",       # Ceftazidime
                  CXM = "-",       # Cefuroxime
                  PEN = "S",       # Benzylpenicillin
                  FOX = "S",       # Cefoxitin
                  stringsAsFactors = FALSE)
  
  b <- eucast_rules(a)
```

NOTE: Using column `mo` as input for `col_mo`.
NOTE: Auto-guessing columns suitable for analysis...OK.
NOTE: Reliability would be improved if these antimicrobial results would be available too: amoxicillin/clavulanic acid (AMC), amikacin (AMK), ampicillin (AMP), azithromycin (AZM), azlocillin (AZL), aztreonam (ATM), cefaloridine (RID), cefepime (FEP), cefotaxime (CTX), cephradine (CED), ceftriaxone (CRO), chloramphenicol (CHL), ciprofloxacin (CIP), clarithromycin (CLR), clindamycin (CLI), flucloxacillin (FLC), cefazolin (CZO), daptomycin (DAP), doxycycline (DOX), ertapenem (ETP), erythromycin (ERY), fosfomycin (FOS), fusidic acid (FUS), gentamicin (GEN), imipenem (IPM), kanamycin (KAN), levofloxacin (LVX), lincomycin (LIN), linezolid (LNZ), meropenem (MEM), mezlocillin (MEZ), minocycline (MNO), moxifloxacin (MFX), nalidixic acid (NAL), neomycin (NEO), netilmicin (NET), nitrofurantoin (NIT), norfloxacin (NOR), novobiocin (NOV), ofloxacin (OFX), oxacillin (OXA), piperacillin (PIP), piperacillin/tazobactam (TZP), polymyxin B (PLB), pristinamycin (PRI), quinupristin/dalfopristin (QDA), rifampicin (RIF), roxithromycin (RXT), sisomicin (SIS), teicoplanin (TEC), tetracycline (TCY), ticarcillin (TIC), tigecycline (TGC), tobramycin (TOB), trimethoprim (TMP), trimethoprim/sulfamethoxazole (SXT)
Fehler in value[[3L]](cond) : 
  ungültiger regulärer Ausdruck '^(abbotic|abboticin|abdizide|abelcet|abelecet|abomacetin|acetohmt|acetylspiramycin|acideclavulanique|acidefusidique|acidoclavulanico|acidofusidico|acidomandelico|acidumclavulanicum|acidumfusidicum|acillin|acneryne|acnesol|acromona|acronize|actilin|actiline|actimoxi|aczone|adesulfonesodium|adobacillin|advocin|aeroquin|aethambutolum|aethionamidum|aetina|aetiva|aizumycin|aknecordeslosung|aknedermerygel|aknemycin|alcephin|alcobon|alconcilox|aldapsone|aldesulfonasodica|aldesulfone|aldesulfonesodique|aldesulfonesodium|alenfral|alexin|alfacet|alficetyn|alflucoz|alfumet|aliporina|almitil|almondacid|alsporin|altacef|ambisome|amblosin|ambofen|ambrocef|ambylan|amcill|amdinocillin|amfipen|amfipenv|amfotericinab|amicacin|amidazin|amidazine|amikacillin|amikacin|amikacinbase|amikacindihydrate|amikacinsulfate|amikacina|amikacine|amikacinum|amikavet|amikin|amiklin|amikozit|aminodeoxykanamycin|aminoform|aminoformaldehyde|aminopar|aminosalicylic|aminosalicylicaci

**My session info:**

`sessionInfo()`

R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252
[4] LC_NUMERIC=C                    LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] AMR_1.3.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.5         lubridate_1.7.9    crayon_1.3.4       dplyr_1.0.2        R6_2.4.1          
 [6] lifecycle_0.2.0    magrittr_1.5       pillar_1.4.6       rlang_0.4.7        rstudioapi_0.11   
[11] effectr_0.20.10.06 vctrs_0.3.4        generics_0.0.2     ellipsis_0.3.1     tools_4.0.2       
[16] glue_1.4.2         purrr_0.3.4        yaml_2.2.1         compiler_4.0.2     pkgconfig_2.0.3   
[21] tidyselect_1.1.0   tibble_3.0.3

**Comment by msberends** [comment]
True, but 1.4.0 was released today 😃 

Might not come up in your updated packages list until tomorrow, so please let me know if you still get this after you’ve installed the newest release.

**Comment by nrkoehler** [comment]
Oh, sorry. I didn't notice. :-) I will check it out now.

**Comment by nrkoehler** [comment]
It works just fine. Thanks a lot!

**Comment by msberends** [comment]
Great! Enjoy!
